server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      #enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://116.125.141.168:23306/yosi?useSSL=false&serverTimezone=Asia/Seoul&chractoerEncoding=UTF-8
    username: lakecomo
    password: lakecomoqweasd!23

  devtools:
    livereload:
      enabled: true


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bizmap.vo
  configuration:
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 1000


logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%logger.%method:line-%line] - %msg%n"
  file:
    name: logs/bizmap.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      file-name-pattern: "${logging.file.name}.%d{yyyy-MM-dd}.%i.gz"
      max-history: 30
  level:
    root: info
    com.bizmap: debug
    # mybatis query log
    jdbc:
      sqlonly: off
      sqltiming: debug
      resultsettable: off
      audit: off
      resultset: off
      connection: off

devtools:
  livereload:
    enabled: true